version: '3'
services:

  # Base Images

  php73-fpm-buster-base:
    image: my127/akeneo:7.3-fpm-buster${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: 7.3
        BASEOS: buster

  php74-fpm-buster-base:
    image: my127/akeneo:7.4-fpm-buster${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: 7.4
        BASEOS: buster

  php74-fpm-bullseye-base:
    image: my127/akeneo:7.4-fpm-bullseye${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: 7.4
        BASEOS: bullseye

  php80-fpm-bullseye-base:
    image: my127/akeneo:8.0-fpm-bullseye${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: "8.0"
        BASEOS: bullseye

  php81-fpm-bullseye-base:
    image: my127/akeneo:8.1-fpm-bullseye${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: 8.1
        BASEOS: bullseye

  php82-fpm-bullseye-base:
    image: my127/akeneo:8.2-fpm-bullseye${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: 8.2
        BASEOS: bullseye

  php83-fpm-bookworm-base:
    image: my127/akeneo:8.3-fpm-bookworm${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: 8.3
        BASEOS: bookworm

  # Console Images

  php73-fpm-buster-console:
    image: my127/akeneo:7.3-fpm-buster-console${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: 7.3
        BASEOS: buster

  php74-fpm-buster-console:
    image: my127/akeneo:7.4-fpm-buster-console${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: 7.4
        BASEOS: buster

  php74-fpm-bullseye-console:
    image: my127/akeneo:7.4-fpm-bullseye-console${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: 7.4
        BASEOS: bullseye

  php80-fpm-bullseye-console:
    image: my127/akeneo:8.0-fpm-bullseye-console${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: "8.0"
        BASEOS: bullseye

  php81-fpm-bullseye-console:
    image: my127/akeneo:8.1-fpm-bullseye-console${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: 8.1
        BASEOS: bullseye

  php82-fpm-bullseye-console:
    image: my127/akeneo:8.2-fpm-bullseye-console${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: 8.2
        BASEOS: bullseye

  php83-fpm-bookworm-console:
    image: my127/akeneo:8.3-fpm-bookworm-console${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: 8.3
        BASEOS: bookworm
