version: '3'
services:

  # Base Images

  php73-fpm-stretch-base:
    image: my127/akeneo:7.3-fpm-stretch${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: 7.3
        BASEOS: stretch

  # Console Images

  php73-fpm-stretch-console:
    image: my127/akeneo:7.3-fpm-stretch-console${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: 7.3
        BASEOS: stretch
